# Generated by Django 5.2.6 on 2025-09-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        # Remove fields that don't exist in the current model
        migrations.RemoveField(
            model_name='recommendation',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommender_image',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='skills_mentioned',
        ),
    ]
